### ISSUE TITLE
Layout/FirstArgumentIndentation config options do not match rubocop mainline

### ISSUE THREAD

**Issue by mcordell** [codeclimate/codeclimate-rubocop#251]
Hello,

When running the rubocop engine on the 0.88.0 channel my code climate build fails with:

```
/usr/local/bundle/gems/rubocop-0.88.0/lib/rubocop/config_validator.rb:168:in `block (2 levels) in validate_enforced_styles': invalid EnforcedStyle 'special_for_inner_method_call_in_parentheses' for Layout/FirstArgumentIndentation found in .rubocop-https---raw-githubusercontent-com-q-centrix-hound-cdf1eb2cd7aee36f9ff9ffb619546434f2f4d232-config-style-guides-ruby-yml (RuboCop::ValidationError)
```

[Offending config line can be found here](https://github.com/q-centrix/hound/blob/cdf1eb2cd7aee36f9ff9ffb619546434f2f4d232/config/style_guides/ruby.yml#L168)

The parameter `special_for_inner_method_call_in_parentheses` is a valid parameter for this cop, and has been for many versions [as far as I can tell](https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml#L590-L613).

The inconsistency appears to be here within the rubocop code climate engine:

https://github.com/codeclimate/codeclimate-rubocop/compare/channel/rubocop-0-88#diff-c080539d8dd39209035b0af8a3306e35R6-R7

Changing the line to 'consistent' allowed my build to pass but it seems like 'special_for_inner_method_call_in_parentheses' should work.

**Comment by britneywright** [comment]
I see this issue beginning with channel 0.86.0. The error message I see is:
 
```
/usr/local/bundle/gems/rubocop-0.86.0/lib/rubocop/config_validator.rb:168:in `block (2 levels) in validate_enforced_styles': invalid EnforcedStyle 'special_for_inner_method_call_in_parentheses' for Layout/FirstArgumentIndentation found in .rubocop.yml (RuboCop::ValidationError)
Valid choices are: consistent, align_parentheses
```

The valid choices it indicates seem to be for [FirstParameterIndentation](https://github.com/rubocop-hq/rubocop/blob/v0.88.0/config/default.yml#L694-L707) rather than [FirstArgumentIndentation](https://github.com/rubocop-hq/rubocop/blob/v0.88.0/config/default.yml#L589-L612)

**Comment by filipesperandio** [comment]
@britneywright I guess we probably just need to fix the default config to use the `FirstArgumentIndentation` instead to keep the current behaviour 
https://github.com/codeclimate/codeclimate-rubocop/blob/master/config/style_guides/ruby.yml#L166

**Comment by britneywright** [comment]
@mcordell this is fixed now if you install the the latest version of the 0-88-0 channel and update your .codeclimate.yml to disable the Mry config upgrader. This [PR](https://github.com/codeclimate/codeclimate-rubocop/pull/260) explains the issue and the approach. We use Mry to bring old RuboCop configs up to the standards of newer versions automatically, but Mry itself has fallen behind so there were some negative impacts. So we've added the option to disable that. Your config should be updated to look something like:
 
```
rubocop:
  enabled: true
  channel: rubocop-0-88
  checks:
    mry:
      disabled: true
```

**Comment by joaovitoras** [comment]
@filipesperandio this fix is not inherited in the most current versions?
I have the same issue with channel running rubocop 1.9.1
```ruby
/usr/local/bundle/gems/rubocop-1.9.1/lib/rubocop/config_validator.rb:188:in `block (2 levels) in validate_enforced_styles': invalid EnforcedStyle 'special_for_inner_method_call_in_parentheses' for Layout/FirstArgumentIndentation found in .rubocop/layout.yml (RuboCop::ValidationError)
Valid choices are: consistent, align_parentheses
	from /usr/local/bundle/gems/rubocop-1.9.1/lib/rubocop/config_validator.rb:177:in `each'
	from /usr/local/bundle/gems/rubocop-1.9.1/lib/rubocop/config_validator.rb:177:in `block in validate_enforced_styles'
        # ...
```

**Comment by irphilli** [comment]
@britneywright I'm also still seeing this with the 1-23-0 channel, even with mry disabled. Would this be the same issue, or a different one?
